/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'Rysom_000' at '10/6/16 2:51 PM' with Gradle 3.0
 *
 * @author Rysom_000, @date 10/6/16 2:51 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
